- hosts: localhost

  roles:
  - developer-workstation
  - { role: ngetchell.vscode, become: true, tags: 'vscode' }
  - { role: cmprescott.chrome, become: true, tags: 'chrome' }

  vars_prompt:
    - name: "ssh_key_passphrase"
      prompt: "Enter SSH key passphrase"
      private: yes

