- hosts: local
  #  tasks:
  #    - name: Install playbook dependencies
  #      local_action: command ansible-galaxy install -r requirements.yml
  roles:
    - common
    - dotfiles
    - { role: cmprescott.chrome, become: true }

