---
- name: Dotfiles - Clone dotfiles repo
  git:
    repo: "{{ item['url'] }}"
    dest: "{{ item['target'] }}"
    recursive: yes
  with_items: "{{ dotfiles|default([]) }}"

- name: Dotfiles - Run dotfiles installer
  command: "{{ item['target'] }}/install"
  with_items: "{{ dotfiles|default([]) }}"

- name: Dofiles - Set ZDOTDIR
  become: true
  lineinfile:
    dest: /etc/zsh/zshenv
    regexp: ^ZDOTDIR=
    line: ZDOTDIR=$HOME/.config/zsh
