---
- name: Dotfiles - Clone dotfiles repo
  git:
    repo: "{{ item['repo'] }}"
    dest: "{{ item['dest'] }}"
    recursive: yes
  with_items: "{{ dotfiles|default([]) }}"

- name: Dotfiles - Run dotfiles installer
  command: "{{ item['dest'] }}/{{ item['runner'] }}"
  with_items: "{{ dotfiles|default([]) }}"

- name: Dofiles - Set ZDOTDIR
  become: true
  lineinfile:
    dest: /etc/zsh/zshenv
    regexp: ^ZDOTDIR=
    line: ZDOTDIR=$HOME/.config/zsh
