# Lines configured by zsh-newuser-install
HISTFILE=$XDG_DATA_HOME/zsh_histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd nomatch notify
bindkey -v
# End of lines configured by zsh-newuser-install

# The following lines were added by compinstall
zstyle :compinstall filename "$XDG_CONFIG_HOME/zsh/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall

# enable suggestions for commands not found
source /etc/zsh_command_not_found

# Aliases
alias ls='ls --color=auto'
alias grep='grep --color'
alias la='ls -la'
alias l='ls'
alias cp='cp -i'
alias mv='mv -i'

