- name: Fonts - Ensure {{ fonts.install_dir }} exists
  file:
    path: "{{ fonts.install_dir }}"
    state: directory

- name: Fonts - Download each font
  unarchive:
    remote_src: yes
    src: "{{ item['archive_url'] }}"
    dest: "{{ fonts.install_dir }}"    
  with_items: "{{ fonts.font_list }}"
  register: archive_contents

- name: Fonts - Update cache
  command: fc-cache -f -v
  become: true
  when: archive_contents is changed


