---
- include: setup.yml
  tags: [always]

- include: zsh.yml
  tags: [zsh]

- include: xdg.yml
  tags: [xdg]

- include: nvm.yml
  tags: [nvm]

- include: sdkman.yml
  tags: [sdkman]

- include: neovim.yml
  tags: [neovim]

- include: tmux.yml
  tags: [tmux]

- include: packages.yml
  tags: [packages]

- include: sysctl.yml
  tags: [sysctl]

- include: fonts.yml
  tags: [fonts]

- include: binfiles.yml
  tags: [binfiles]

- include: teardown.yml
  tags: [always]

