---
- name: Neovim - Add PPA
  apt_repository:
    repo: 'ppa:neovim-ppa/unstable'
  become: true

- name: Neovim - Install
  apt: 
    name: neovim
  become: true

- name: Neovim - Create config and data dirs
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - "{{ xdg.XDG_CONFIG_HOME }}/nvim"
    - "{{ xdg.XDG_DATA_HOME }}/nvim/site/autoload"

- name: Neovim - Clone vim-plug
  git:
    repo: https://github.com/junegunn/vim-plug.git
    dest: "{{ xdg.XDG_DATA_HOME }}/vim-plug"

- name: Neovim - Copy plug.vim into autoload
  copy:
    src: "{{ xdg.XDG_DATA_HOME }}/vim-plug/plug.vim"
    dest: "{{ xdg.XDG_DATA_HOME }}/nvim/site/autoload/"

- name: Neovim - Copy init.vim into config
  copy:
    src: neovim/init.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"

# TODO: this always registers as change
- name: Neovim - Install plugins
  shell: >
    nvim +'PlugInstall --sync' +qa

- name: Neovim - Point vi to nvim
  alternatives:
    link: /usr/bin/vi
    name: vi
    path: /usr/bin/nvim
  become: true

- name: Neovim - Point vim to nvim
  alternatives:
    link: /usr/bin/vim
    name: vim
    path: /usr/bin/nvim
  become: true
