---
- name: SDKMAN - Check if .sdkman exists
  stat: path={{ansible_env.HOME}}/.sdkman
  register: p

- name: SDKMAN - Download install script
  block:  
    - name: SDKMAN - Download install script
      get_url:
        url: https://get.sdkman.io
        mode: 0755
        dest: "{{ _tmp.path }}/sdkman_install"
    - name: SDKMAN - Run install script
      shell: "{{ _tmp.path }}/sdkman_install"
  when: not p.stat.exists

