---
- name: SSH - Create Github key
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: ".ssh/{{ ansible_env.USER }}@{{ ansible_hostname }}"
    ssh_key_passphrase: "{{ ssh_key_passphrase }}"
