---
#
# Remove some standard folders from home folder
# See http://jamesmcminn.com/2012/12/removing-entries-from-nautilus-3-6-places/
#
- name: XDG - Write user-dirs.dirs
  copy: 
    src: user-dirs.dirs
    dest: "{{ ansible_env.HOME }}/.config/user-dirs.dirs"
    backup: yes

- name: XDG - Write user-dirs.conf
  copy: 
    src: user-dirs.conf
    dest: "{{ ansible_env.HOME }}/.config/user-dirs.conf"
    backup: yes

- name: XDG - Copy template files
  copy: 
    src: 'Empty Document'
    dest: "{{ ansible_env.HOME }}/Templates/Empty Document"

- name: XDG - Delete Public directory
  file:
    path: "{{ ansible_env.HOME }}/Public"
    state: absent

- name: XDG - Delete Documents directory
  file:
    path: "{{ ansible_env.HOME }}/Documents"
    state: absent

- name: XDG - Delete Music directory
  file:
    path: "{{ ansible_env.HOME }}/Music"
    state: absent

- name: XDG - Delete Pictures directory
  file:
    path: "{{ ansible_env.HOME }}/Pictures"
    state: absent

- name: XDG - Delete Videos directory
  file:
    path: "{{ ansible_env.HOME }}/Videos"
    state: absent

