---
# Create XDG folders
- name: XDG - Create data/config/cache folders
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
  loop:
    - "{{ xdg.XDG_DATA_HOME }}"
    - "{{ xdg.XDG_CONFIG_HOME }}"
    - "{{ xdg.XDG_CACHE_HOME }}"

# Define XDG env vars in bash/zsh
- name: XDG - Add env vars to bash/zsh
  blockinfile:
    dest: "{{ item }}"
    create: yes
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK - xdg.yml"
    block: |
      export XDG_CONFIG_HOME={{ xdg.XDG_CONFIG_HOME }}
      export XDG_DATA_HOME={{ xdg.XDG_DATA_HOME }}
      export XDG_CACHE_HOME={{ xdg.XDG_CACHE_HOME }}
  loop:
    - "{{ ansible_env.HOME }}/.bashrc"
    - "{{ xdg.XDG_CONFIG_HOME }}/zsh/.zshrc"

# Remove some standard folders from home folder
# See http://jamesmcminn.com/2012/12/removing-entries-from-nautilus-3-6-places/
- name: XDG - Write user-dirs.dirs
  copy: 
    src: user-dirs.dirs
    dest: "{{ ansible_env.HOME }}/.config/user-dirs.dirs"
    backup: yes

- name: XDG - Write user-dirs.conf
  copy: 
    src: user-dirs.conf
    dest: "{{ ansible_env.HOME }}/.config/user-dirs.conf"
    backup: yes

- name: XDG - Copy template files
  copy: 
    src: 'Empty Document'
    dest: "{{ ansible_env.HOME }}/Templates/Empty Document"

- name: XDG - Delete unused home directories
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent
  loop:
    - Public
    - Documents
    - Music
    - Pictures
    - Videos

