---
- name: ZSH - Install ZSH
  apt:
    name: zsh
  become: true

- name: ZSH - Set ZDOTDIR
  lineinfile:
    dest: /etc/zsh/zshenv
    backup: yes
    line: export ZDOTDIR="$HOME/.config/zsh"
  become: yes

- name: ZSH - Switch shell to zsh
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true

- name: ZSH - Clone Pure
  git:
    repo: https://github.com/sindresorhus/pure.git
    dest: "{{ XDG_DATA_HOME }}/pure"

- name: ZSH - Symlink pure.zsh
  file:
    src: "{{ XDG_DATA_HOME }}/pure/pure.zsh"
    dest: /usr/local/share/zsh/site-functions/prompt_pure_setup
    state: link
  become: true

- name: ZSH - Symlink async.zsh
  file:
    src: "{{ XDG_DATA_HOME }}/pure/async.zsh"
    dest: /usr/local/share/zsh/site-functions/async
    state: link
  become: true

- name: ZSH - Base 16 shell
  git:
    repo: https://github.com/chriskempson/base16-shell.git
    dest: "{{ XDG_DATA_HOME }}/base16-shell"

- name: ZSH - Create dircolors folder
  file:
    path: "{{ XDG_DATA_HOME }}/dircolors"
    recurse: yes
    state: directory

- name: ZSH - Copy dircolors file
  copy:
    src: dircolors.base16.dark
    dest: "{{ XDG_DATA_HOME }}/dircolors/dircolors.base16.dark"

- name: ZSH - Create config folder
  file:
    path: "{{ XDG_CONFIG_HOME }}/zsh"
    recurse: yes
    state: directory

- name: ZSH - Copy zshrc
  copy:
    src: zshrc
    dest: "{{ XDG_CONFIG_HOME }}/zsh/.zshrc"



