---
- name: ZSH - Install ZSH
  apt:
    name: zsh
  become: true

- name: ZSH - Switch shell to zsh
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true

- name: ZSH - Pure prompt
  git:
    repo: https://github.com/sindresorhus/pure
    dest: "{{ ansible_env.HOME }}/.config/pure"
  register: g

- name: ZSH - Symlink pure.zsh
  file:
    src: "{{ ansible_env.HOME }}/.config/pure/pure.zsh"
    dest: /usr/local/share/zsh/site-functions/prompt_pure_setup
    state: link
  become: true

- name: ZSH - Symlink async.zsh
  file:
    src: "{{ ansible_env.HOME }}/.config/pure/async.zsh"
    dest: /usr/local/share/zsh/site-functions/async
    state: link
  become: true

- name: ZSH - Base 16 shell
  git:
    repo: https://github.com/chriskempson/base16-shell.git
    dest: "{{ ansible_env.HOME }}/.config/base16-shell"

- name: ZSH - Copy dircolors file
  copy:
    src: dircolors.base16.dark
    dest: "{{ ansible_env.HOME }}/.dircolors.base16.dark"

- name: ZSH - Copy .zshrc
  copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"

