---
- name: ZSH - Install ZSH
  apt: name=zsh state=present
  become: true

- name: ZSH - Get zsh path
  command: which zsh 
  register: zsh_path

- name: ZSH - Switch shell to {{ zsh_path.stdout }}
  user: name={{ ansible_user_id }} shell={{ zsh_path.stdout }}
  become: true
