---
- name: ZSH - Install ZSH
  apt:
    name: zsh
  become: true

- name: ZSH - Set ZDOTDIR
  lineinfile:
    dest: "{{ zsh.zshenv_dir }}"
    backup: yes
    line: export ZDOTDIR="$HOME/.config/zsh"
  become: yes

- name: ZSH - Create config folder
  file:
    path: "{{ xdg.XDG_CONFIG_HOME }}/zsh"
    recurse: yes
    state: directory

- name: ZSH - Switch shell to zsh
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true

- name: ZSH - Clone Pure
  git:
    repo: https://github.com/sindresorhus/pure.git
    dest: "{{ xdg.XDG_DATA_HOME }}/pure"

- name: ZSH - Symlink pure.zsh
  file:
    src: "{{ xdg.XDG_DATA_HOME }}/pure/pure.zsh"
    dest: "{{ zsh.fpath }}/prompt_pure_setup"
    state: link
  become: true

- name: ZSH - Symlink async.zsh
  file:
    src: "{{ xdg.XDG_DATA_HOME }}/pure/async.zsh"
    dest: "{{ zsh.fpath }}/async"
    state: link
  become: true

- name: ZSH - Base 16 shell
  git:
    repo: https://github.com/chriskempson/base16-shell.git
    dest: "{{ xdg.XDG_DATA_HOME }}/base16-shell"

- name: ZSH - Create dircolors folder
  file:
    path: "{{ xdg.XDG_DATA_HOME }}/dircolors"
    recurse: yes
    state: directory

- name: ZSH - Copy dircolors file
  copy:
    src: zsh/dircolors.base16.dark
    dest: "{{ xdg.XDG_DATA_HOME }}/dircolors/dircolors.base16.dark"

- name: ZSH - .zshrc
  blockinfile:
    dest: "{{ xdg.XDG_CONFIG_HOME }}/zsh/.zshrc"
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK - zsh.yml"
    block: |
      # Lines configured by zsh-newuser-install
      HISTFILE={{ xdg.XDG_DATA_HOME }}/zsh_histfile
      HISTSIZE=1000
      SAVEHIST=1000
      setopt appendhistory autocd nomatch notify
      bindkey -v
      # End of lines configured by zsh-newuser-install
      # The following lines were added by compinstall
      zstyle :compinstall filename "{{ xdg.XDG_CONFIG_HOME }}/zsh/.zshrc"
      autoload -Uz compinit
      compinit
      # End of lines added by compinstall
      # enable suggestions for commands not found
      source /etc/zsh_command_not_found
      # Aliases
      alias ls='ls --color=auto'
      alias grep='grep --color'
      alias la='ls -la'
      alias l='ls'
      alias cp='cp -i'
      alias mv='mv -i'
      # pure prompt
      autoload -U promptinit; promptinit
      prompt pure
      # Load base-16 shell colors
      BASE16_SHELL={{ xdg.XDG_DATA_HOME }}/base16-shell
      [ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
      # dircolors
      eval `dircolors {{ xdg.XDG_DATA_HOME }}/dircolors/dircolors.base16.dark`

- name: ZSH - Ensure ~/.zshrc is absent
  file:
    path: "{{ ansible_env.HOME }}/.zshrc"
    state: absent



