---
  - name: install developer font - make temp dir
    file: path=../tmp state=directory mode=0755

  - name: install developer font - download font
    get_url:
      url: "{{ fonts['archive_url'] }}"
      dest: ../tmp/source_code_pro.tar.gz
      mode: 0755

  - name: install developer font - unzip downloaded font
    unarchive: src=../tmp/source_code_pro.tar.gz dest=../tmp

  - name: install developer font - make fonts directory
    file: path={{ fonts['install_dir'] }} state=directory mode=0755

  - name: install developer font - copy fonts
    copy: src=../tmp/{{ fonts['archive_dir'] }} dest={{ fonts['install_dir'] }} mode=0755
    register: copy_fonts

  - name: install developer font - font cache
    command: fc-cache -f -v
    become: true
    when: copy_fonts.changed

#  - name: install developer font - set system font
#    gconftool2:
#      key: /apps/gnome-terminal/profiles/Default/font
#      string: "Source Code Pro Semi-Bold 12"
#
#  - name: install developer font - dont use default system font in terminal
#    gconftool2:
#      key: /apps/gnome-terminal/profiles/Default/use_system_font
#      ool: false
