---
- name: Fonts - Download Source Code Pro
  get_url:
    url: "{{ fonts['archive_url'] }}"
    dest: "{{ tmp_dir }}/source_code_pro.tar.gz"

- name: Fonts - Unzip downloaded font
  unarchive: src={{ tmp_dir }}/source_code_pro.tar.gz dest={{ tmp_dir }}

- name: Fonts - Make local font directory
  file: path={{ fonts['install_dir'] }} state=directory mode=0755

- name: Fonts - Copy font to local directory
  copy: src={{ tmp_dir }}/{{ fonts['archive_dir'] }} dest={{ fonts['install_dir'] }} mode=0755
  register: copy_fonts

- name: Fonts - Update font cache
  command: fc-cache -f -v
  become: true
  when: copy_fonts.changed

