---
- name: Fonts - Create temp extract folder
  file: path={{ tmp_dir }}/fonts state=directory mode=0755

- name: Fonts - Download
  get_url:
    url: "{{ fonts['archive_url'] }}"
    dest: "{{ tmp_dir }}/{{ fonts['archive_file'] }}"

- name: Fonts - Unzip
  unarchive: src={{ tmp_dir }}/{{ fonts['archive_file'] }} dest={{ tmp_dir }}/fonts/{{ fonts['archive_root_dir'] }}

- name: Fonts - Make local font directory
  file: path={{ fonts['install_dir'] }} state=directory mode=0755

- name: Fonts - Copy font to local directory
  copy: src={{ tmp_dir }}/fonts/{{ fonts['archive_root_dir'] }} dest={{ fonts['install_dir'] }} mode=0755
  register: copy_fonts

- name: Fonts - Update font cache
  command: fc-cache -f -v
  become: true
  when: copy_fonts.changed

