---
- name: Neovim - Add repository
  command: add-apt-repository -y ppa:neovim-ppa/unstable
  become: true

- name: Neovim - Install packages
  apt: name=neovim state=present update_cache=yes
  become: true

- name: Neovim - Point vi to nvim
  alternatives: link=/usr/bin/vi name=vi path=/usr/bin/nvim
  become: true

- name: Neovim - Point vim to nvim
  alternatives: link=/usr/bin/vim name=vim path=/usr/bin/nvim
  become: true

