---
- name: SDKMAN - Download install script
  get_url:
    url: https://get.sdkman.io
    dest: "{{ tmp_dir }}/sdkman_install"
    mode: 0755

- name: SDKMAN - Execute install script
  shell: "{{ tmp_dir }}/sdkman_install"
  args:
    creates: "{{ ansible_env.HOME}}/.sdkman"

- name: SDKMAN - Delete zshrc (managed by dotfiles)
  file: path={{ ansible_env.HOME }}/.zshrc state=absent

