---
- name: Typora - Add key
  apt_key: keyserver=keyserver.ubuntu.com id=BA300B7755AFCFAE
  become: true

- name: Typora - Add repository
  command: add-apt-repository -y "deb https://typora.io linux/"
  become: true

- name: Typora - Install packages
  apt: name=typora state=present update_cache=yes
  become: true

