---
- name: Install ZSH
  become: true
  apt: name=zsh state=present update_cache=yes cache_valid_time=3600

- name: Get zsh path
  command: which zsh 
  register: zsh_path

- name: Switch shell to zsh
  user: name={{ ansible_user_id }} shell=zsh_path.stdout
